name: VCMI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/VCMI.yml
      - CMakeLists.txt
      - CMakePresets.txt
      - include/*
      - tests/*

  pull_request:
    paths:
      - .github/workflows/VCMI.yml
      - CMakeLists.txt
      - include/*
      - tests/*

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux-qt6
            generator: Unix Makefiles
            os: ubuntu-22.04
            test: 0
            preset: linux-clang-test
          - platform: linux
            generator: Unix Makefiles
            os: ubuntu-22.04
            test: 1
            preset: linux-gcc-test
            generator: Unix Makefiles
          - platform: linux
            os: ubuntu-20.04
            test: 0
            preset: linux-gcc-debug
            generator: Unix Makefiles
          - platform: mac-intel
            os: macos-12
            test: 0
            pack: 1
            pack_type: Release
            extension: dmg
            preset: macos-conan-ninja-release
            conan_profile: macos-intel
            conan_options: --options with_apple_system_libs=True
            artifact_platform: intel
            generator: MinGW Makefiles
          - platform: mac-arm
            os: macos-12
            test: 0
            pack: 1
            pack_type: Release
            extension: dmg
            preset: macos-arm-conan-ninja-release
            conan_profile: macos-arm
            conan_options: --options with_apple_system_libs=True
            artifact_platform: arm
            generator: MinGW Makefiles
          - platform: ios
            os: macos-12
            test: 0
            pack: 1
            pack_type: Release
            extension: ipa
            preset: ios-release-conan-ccache
            conan_profile: ios-arm64
            conan_options: --options with_apple_system_libs=True
            generator: MinGW Makefiles
          - platform: msvc
            os: windows-latest
            test: 0
            pack: 1
            pack_type: RelWithDebInfo
            extension: exe
            preset: windows-msvc-release-ccache
            generator: Visual Studio 17
          - platform: mingw
            os: ubuntu-22.04
            test: 0
            pack: 1
            pack_type: Release
            extension: exe
            cpack_args: -D CPACK_NSIS_EXECUTABLE=`which makensis`
            cmake_args: -G Ninja
            preset: windows-mingw-conan-linux
            conan_profile: mingw64-linux.jinja
            generator: MinGW Makefiles
          - platform: mingw-32
            os: ubuntu-22.04
            test: 0
            pack: 1
            pack_type: Release
            extension: exe
            cpack_args: -D CPACK_NSIS_EXECUTABLE=`which makensis`
            cmake_args: -G Ninja
            preset: windows-mingw-conan-linux
            conan_profile: mingw32-linux.jinja
            generator: MinGW Makefiles
          - platform: android-32
            os: ubuntu-22.04
            extension: apk
            preset: android-conan-ninja-release
            conan_profile: android-32
            conan_options: --conf tools.android:ndk_path=$ANDROID_NDK_ROOT
            artifact_platform: armeabi-v7a
            generator: Unix Makefiles
          - platform: android-64
            os: ubuntu-22.04
            extension: apk
            preset: android-conan-ninja-release
            conan_profile: android-64
            conan_options: --conf tools.android:ndk_path=$ANDROID_NDK_ROOT
            artifact_platform: arm64-v8a
            generator: Unix Makefiles

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Conan setup
        if: "${{ matrix.conan_profile != '' }}"
        run: |
          pip3 install 'conan<2.0'
          conan profile new default --detect
          conan install . \
            --install-folder=conan-generated \
            --no-imports \
            --build=never \
            --profile:build=default \
            --profile:host=CI/conan/${{ matrix.conan_profile }} \
            ${{ matrix.conan_options }}
        env:
          GENERATE_ONLY_BUILT_CONFIG: 1

      - name: Dependencies
        run: source '${{github.workspace}}/CI/${{matrix.platform}}/before_install.sh'
        env:
          VCMI_BUILD_PLATFORM: x64

    # ensure the ccache for each PR is separate so they don't interfere with each other
    # fall back to ccache of the vcmi/vcmi repo if no PR-specific ccache is found
      - name: ccache for PRs
        uses: hendrikmuhs/ccache-action@v1.2
        if: ${{ github.event.number != '' }}
        with:
          key: ${{ matrix.preset }}-PR-${{ github.event.number }}
          restore-keys: |
            ${{ matrix.preset }}-PR-${{ github.event.number }}
            ${{ matrix.preset }}-no-PR
          # actual cache takes up less space, at most ~1 GB
          max-size: "5G"
          verbose: 2

      - name: ccache for everything but PRs
        uses: hendrikmuhs/ccache-action@v1.2
        if: ${{ (github.repository == 'vcmi/vcmi' && github.event.number == '' && github.ref == 'refs/heads/develop') ||  github.repository != 'vcmi/vcmi' }}
        with:
          key: ${{ matrix.preset }}-no-PR
          restore-keys: |
            ${{ matrix.preset }}-no-PR
          # actual cache takes up less space, at most ~1 GB
          max-size: "5G"
          verbose: 2

      - name: Configure
        run: |
          if [[ ${{matrix.preset}} == linux-gcc-test ]]; then GCC13=1; fi
          cmake -DENABLE_CCACHE:BOOL=ON --preset ${{ matrix.preset }} ${GCC13:+-DCMAKE_C_COMPILER=gcc-13 -DCMAKE_CXX_COMPILER=g++-13}

      # - name: Build
      #   run: |
      #     cmake --build --preset ${{matrix.preset}}

      - name: Generate project files
        run: cmake . -B build -G "${{ matrix.generator }}" -DCMAKE_CXX_STANDARD=${{ matrix.cxx-std }} -DDYLIB_BUILD_TESTS=ON -DDYLIB_WARNING_AS_ERRORS=ON

      - name: Build dynamic library and unit tests
        run: cmake --build build

      - name: Run unit tests
        working-directory: build
        run: ctest

      - name: Generate code coverage
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.cxx-std == 20 }}
        run: gcov -abcfu build/CMakeFiles/unit_tests.dir/tests/tests.cpp.gcda

      - name: Send coverage to codecov.io
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.cxx-std == 20 }}
        uses: codecov/codecov-action@v3
        with:
          files: dylib.hpp.gcov

  memory_check:
    name: memory check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update packages
        run: sudo apt update

      - name: Install valgrind
        run: sudo apt install -y valgrind

      - name: Generate tests build file
        run: cmake . -B build -DCMAKE_CXX_STANDARD=20 -DDYLIB_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Build unit tests
        run: cmake --build build

      - name: Run unit tests with valgrind
        working-directory: build
        run: valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./unit_tests

  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: cpplint --linelength=140 --filter=-whitespace/indent,-whitespace/parens include/dylib.hpp
